### Welcome to Jekyll Webpack Boilerplate
#
# This config file contains the config of your webpages
# You may also want to update /config/webpack.pwa.js in case you want to generate a Progressive Web App

title: Jekyll-Webpack Boilerplate
email: chpmnrssll@gmail.com
description: An extremely optimized Jekyll-Webpack website

# baseurl must match publicPath in webpack.prod.js
baseurl: /jekyll-webpack # the subpath of your site, e.g. /blog
url: https://chpmnrssll.github.io # the base hostname & protocol for your site, e.g. http://example.com

theme_color: '#0d5173'
twitter_username: chpmnrssll
github_username:  chpmnrssll
author: Russell Chapman
logo: assets/images/large-logo.png
twitter:
  username: chpmnrssll
social:
  name: Russell Chapman
  links:
    - https://linkedin.com/in/russell-chapman-343013153/
    - https://github.com/chpmnrssll

languages: ["en"]
ampdir: amp

### Google webmaster tools, Google Analytics, Doorbell and Cookie consent uncomment and put the API key
#webmaster_verifications:
#  google: verification_code
#google_analytics: id
#doorbell:
#  id: doorbell_id
#  appKey: doorbell_appKey

#cookie_consent: true

### Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - octopress-minify-html
  - jekyll-multiple-languages-plugin
  - amp-jekyll

### Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - _src
  - _images
  - LICENSE
  - package.json
  - README.md
  - webpack.config.js
  - yarn-error.log
  - yarn.lock
  - config
  - optimization-fix
  - optimization-fix-this-file-is-ignored.js
  - icon.png
